networks:
  backend:

#volumes:
#  database:

services:
  concordia:
    image: ghost:alpine
    networks:
      - backend
    ports:
      - 2368:2368
    restart: on-failure:5
    volumes:
     - './content/data:/var/lib/ghost/content/data'
     - './content/images:/var/lib/ghost/content/images'
     - './content/media:/var/lib/ghost/content/media'
     - './content/settings:/var/lib/ghost/content/settings'
     - './content/themes:/var/lib/ghost/content/themes'
     #- './test:/var/lib/ghost'
    environment:
      - database__client=sqlite3
      - database__connection__filename="content/data/ghost.db" 
      - database__useNullAsDefault=true 
      - database__debug=false 
      - NODE_ENV=development 