networks:
  backend:

volumes:
  ghost-db:

services:
  concordia:
    # image: ghost:alpine
    build: .
    networks:
      - backend
    ports:
      - 2368:2368
    restart: on-failure:5
    volumes:
     - './content/data:/var/lib/ghost/content/data'
     - './content/images:/var/lib/ghost/content/images'
     - './content/media:/var/lib/ghost/content/media'
     - './content/settings:/var/lib/ghost/content/settings'
     - './content/themes:/var/lib/ghost/content/themes'
     - './config.json:/var/lib/ghost/config.development.json'
     - 'ghost-db:/var/lib/ghost/content/data'
    env_file:
      # TODO cp ghost.env -> .ghost.env and adjust keys
      - ./.ghost.env
    environment:
      - database__client=sqlite3
      - database__connection__filename="content/data/ghost.db"
      - database__useNullAsDefault=true
      - database__debug=false
      - NODE_ENV=development

  # TO debug the database
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    ports:
      - 3000:3000
    volumes:
      - 'ghost-db:/config'
