networks:
  backend:
  database:

volumes:
  database:

services:
  concordia:
    image: ghost:alpine
    depends_on:
      - db
    networks:
      - backend
      - database
    ports:
      - 2368:2368
    restart: on-failure:5
    volumes:
     - './content/data:/var/lib/ghost/content/data'
     - './content/images:/var/lib/ghost/content/images'
     - './content/media:/var/lib/ghost/content/media'
     - './content/settings:/var/lib/ghost/content/settings'
     - './content/themes:/var/lib/ghost/content/themes'
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=example
      - database__connection__database=ghost

  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=example
    networks:
      - database  
    volumes:
      - database:/var/lib/mysql
    restart: on-failure:5